services:
  - type: web
    name: rupee-tracker
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false # User must provide this
